build:
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
    coverage:
      environment:
        php:
          version: 7.2
      tests:
        override:
          - command: make test
            coverage:
              file: build/coverage.clover
              format: clover
