build:
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
    coverage:
      tests:
        override:
          - command: make test
            coverage:
              file: build/coverage.clover
              format: clover
